plugins {
    id 'com.android.application'
}

android {
    namespace 'pe.gob.hbc.calculadora'
    compileSdk 35

    defaultConfig {
        applicationId 'pe.gob.hbc.calculadora'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '2.3-mobile-test'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

